### PR TITLE
Moved notice to line 3. Removed the code 'may break unexpectedly' com…

### PR DESCRIPTION
**Pull request by colinmixonn**
…ment

### CODE REVIEW

**Comment by colinmixonn** [comment]
@rgardler-msft, I did all the checks I know to confirm I only changed 1 file. So, unsure why this README change did not pass CI check?

**Comment by rgardler-msft** [comment]
@jasonmesser7 can you take a look at this. CircleCI is reporting:

```bash
#!/bin/bash -eo pipefail
az login \
  --service-principal \
  --tenant $AZURE_SP_TENANT \
  -u $AZURE_SP \
  -p $AZURE_SP_PASSWORD

argument --tenant/-t: expected one argument
```

Looks like $AZURE_SP_TENANT is not set. Probably a glitch in the request but we should be aware of what happened in case we see it multiple times.

**Comment by rgardler-msft** [comment]
I'm going to go ahead and merge anyway. The file looks great and its a trivial change.

**Comment by jasonmesser7** [comment]
@rgardler-msft I suspect this is something CircleCI does within a PR to protect the project and the credentials/service principles from malicious attackers. When the PR was merged it into main the test ran correctly and passed on CircleCI. 

What I suspect is that CircleCI doesn't give permission in the PR to access the core projects environment variables. For example, what if in the PR someone decided to try and attack Azure by deploying 1 million VMs in the test file. If a PR had access to our environment variables and thus service principle, then a malicious attack could simply create a PR and spend on Azure through our SP. 

We may need to update the Readme to specify that in order for a PR to pass the tests a user will have to set up CircleCI in their fork with a service principle from their own Azure subscription.

I suspect why we didn't have this issue before is because all of the other PR's were from branches on the main project we were working on as a contributor and Colins was the first outside PR since CircleCI was set up.

**Comment by rgardler-msft** [comment]
Lets not worry about it for now. We will move to GitHub actions in the future and the solution may be different at that point.

In the interim we can run any code change merges through local tests before merging.

Ross
________________________________

**Pull request merged**
