### PR TITLE
Allow README.md as well as script.md for default file names

### PR DESCRIPTION
**Pull request by lastcoolnameleft**
NOTE:  This PR depends on #10 since I had to fix the pre-commit messages for it to work.  Merge conflict might occur.  

This is a PR for my proposal of Issue #5.

It was essentially these commands:
* Rename files script.md -> README.md
`for file in $(git ls-files | grep script.md | sed -e 's/\(script.md[^/]*\).*/\1/' | uniq); git mv $file $(echo $file | sed -e 's/script.md/README.md/')`

* Refactor code
`git grep -lz script.md | xargs -0 sed -i '' -e 's/script.md/README.md/g'`

* Addition of Environment.get_script_file_name(script_dir)

* replace hard-coding of script.md with env.get_script_file_name()

* Change any "script.md" conditionals to look for "script.md" or "README.md"

### CODE REVIEW

**Comment by lastcoolnameleft** [comment]
Yup, looks like there's a merge conflict due to #11.  Once that's checked in, I'll resolve.  That said, I'd appreciate a look-over to make sure I'm on the right track.

**Comment by SorraTheOrc** [comment]
I've merged #10 so resolving conflicts should now be easy.

I think this is the right approach (I've not tested though). One thought would be to make the `README.md` option `config.default_file`. This would allow us to change it in specific environments should that ever become necessary. That said, I don't have a real use case at this point and I'll merge with "README.md" rather than block on this.

**Comment by SorraTheOrc** [comment]
I have a PR in the queue (#14) which will have conflicts with this PR. I'd really appreciate a review of #14. It's a cool feature, but quite a significant change to the code. 

I'd like to merge this and work soon so that I can resolve the resulting conflicts in #14 in parallel to the review.

**Comment by lastcoolnameleft** [comment]
@rgardler Conflict resolved.  

FYI, I tried adding a "test-legacy" directory which utilized a script.md file to ensure it worked; however, it altered the other test cases too much.  So, I manually tested and it works for me with either README.md or script.md.

**Pull request merged**
